sudo: required

language: java

services:
  - docker
  
before_install:
- docker info
- docker run -d --name postgres -e POSTGRES_PASSWORD=moneygr -e POSTGRES_USER=moneygr -e LC_ALL=C.UTF-8 postgres
- docker run --link postgres:postgres --rm busybox env
- docker run -v ~/.m2:/root/.m2 -v "$PWD":/usr/src -w /usr/src -E SPRING_DATASOURCE_URL='jdbc:postgresql://\${POSTGRES_PORT_5432_TCP_ADDR}:5432/moneygr' maven:3-jdk-8 mvn test
- docker ps -a

script:
  - env
